### ISSUE TITLE
Some number functions are not conformant

### ISSUE THREAD

**Issue by masak** [luksamuk/believe#11]
As mentioned [here](https://github.com/luksamuk/believe/commit/f9d597f662784f17351547a4f9cd29b5ba731cd8#r35600671), [here](https://github.com/luksamuk/believe/commit/f9d597f662784f17351547a4f9cd29b5ba731cd8#r35600684), and [here](https://github.com/luksamuk/believe/commit/f9d597f662784f17351547a4f9cd29b5ba731cd8#r35600695), some of the numeric operations implemented do not align with the Bel source:

* Subtraction of no arguments should work (and return 0)
* Division of no arguments should work (and return 1)
* Division of one argument should return the argument, not its reciprocal

**Comment by luksamuk** [comment]
This an easy fix. I'll assign myself and come up with a commit right away.

**Comment by luksamuk** [comment]
Seems like `nil` was not being recognized as a proper list, which would cause the no-args version of operations to fail. This is fixed now.
