### ISSUE TITLE
'nil' confusion

### ISSUE THREAD

**Issue by masak** [luksamuk/believe#5]
I was slightly surprised to find in the source an interpretation of the spec in which `nil` belongs to two types.

> `bel_pairp` tests whether the element is a _pair_. That is, either it is a proper pair, or it is the symbol `nil`.
>
> Note that Bel does not explicitly specify that `nil` is a pair, but I am assuming it since one can “extract” the _car_ and the _cdr_ of `nil`.

I believe this assumption to be not necessary. Firstly, `nil` is a symbol by spec. [bellanguage.txt](https://sep.yimg.com/ty/cdn/paulgraham/bellanguage.txt?t=1570993483&) uses the phrase "the symbol nil" three times.

(I think it's unstated whether `nil` is actually equal to `'nil`. But this seems a fair assumption. Either way, it's not crucial for the following.)

Secondly,

> `Bel has four fundamental data types: symbols, pairs, characters, and`
> `streams.`

These are mutually exclusive. Something which is a symbol is not a pair.

At this point, it's still reasonable to argue "OK, `nil` is not technically a pair, but if pretending it is in the implementation makes the implementation easier (and that internal detail does not leak out), then it's justified for reasons of simplicity".

But I think it doesn't necessarily make the implementation easier; moreover, I think it makes the implementation prone to hard-to-discover bugs.

Case in point: `xar` and `xdr` can set the `car` and `cdr` slots of _pairs_, but not of `nil`. In the implementation of both of these, there is a check:

```c
    if(!bel_pairp(pair)) {
        return bel_mkerror(
            bel_mkstring("~a is not a pair."),
            bel_mkpair(pair, bel_g_nil));
    }
```

But since `bel_pairp` allows `nil`, no error is signaled for something like `(xar nil 'a)` or `(xdr nil 'd)`. Instead, we get memory corruption, because those functions assume something about the memory layout of `nil` (at `pair->pair->car = val;`) which is not true for symbols.

My suggestion: make `bel_pairp` only return true for real pairs. Put the special case in `bel_prim_car` and `bel_prim_cdr` instead. `bel_atomp` can also be simplified. `bel_proper_list_p` needs a slight modification.

**Comment by masak** [comment]
Oh, and [`atomp`](https://github.com/luksamuk/believe/blob/master/believe-literate.org#atomp) would also come out simpler, as it would only need to check for not-a-pair.

This, incidentally, is in line with the definition in [the Bel source](https://sep.yimg.com/ty/cdn/paulgraham/bel.bel?t=1570993483&):

```
(def atom (x)
  (no (id (type x) 'pair)))
```

**Comment by luksamuk** [comment]
> My suggestion: make `bel_pairp` only return true for real pairs. Put the special case in `bel_prim_car` and `bel_prim_cdr` instead. `bel_atomp` can also be simplified. `bel_proper_list_p` needs a slight modification.

This is reasonable. The `xar` and `xdr` case is enough to make me consider that.
To be honest, after a quick check, `nil` is not a `cons` in Common Lisp as well (though it is indeed considered to be both a `list` and a `symbol` there).

> Oh, and [`atomp`](https://github.com/luksamuk/believe/blob/master/believe-literate.org#atomp) would also come out simpler, as it would only need to check for not-a-pair.

Indeed. I'll make that change too.

**Comment by luksamuk** [comment]
One extra thing to note is that all `bel_prim_*` functions are meant to be wrappers for other operations, unless they were previously implemented. So for example the `car` and `cdr` exceptions for `nil` are not actually implemented in `bel_prim_car` and `bel_prim_cdr`, but are implemented in `bel_car` and `bel_cdr`, which are internal and used on other parts of the program as well.
