### ISSUE TITLE
Wrong order between lexical and dynamic lookup

### ISSUE THREAD

**Issue by masak** [luksamuk/believe#8]
[This comment](http://www.arclanguage.org/item?id=21359) (2nd point) expresses surprise that dynamic lookup happens _before_ lexical lookup in the language. Indeed, that sounded surprising to me too, in a "that can't be right" fashion...

...but then I checked, and the language _is_ specified like that, with no room for doubt.

From [the language guide](https://sep.yimg.com/ty/cdn/paulgraham/bellanguage.txt?t=1570993483&):

```
Dynamic bindings take precendence over lexical bindings, which take 
precedence over global ones.

[...]

Let's skip down to lookup and see what it does. It checks, in order, 
whether the variable has a dynamic binding, a lexical binding, or a 
global binding.
```

And [the Bel source](https://sep.yimg.com/ty/cdn/paulgraham/bel.bel?t=1570993483&) also makes this clear:

```
(def lookup (e a s g)
  (or (binding e s)
      (get e a id)
      (get e g id)
      (case e
        scope (cons e a)
        globe (cons e g))))
```

As the commenter points out, this is very surprising. But it _is_ spec, and (what's worse) large parts of the Bel source seem to rest on it being specified like that.

I noticed that the source code for `believe` currently has lookups in the order lexical, dynamic, global. It should be dynamic, lexical, global.

In my own implementation of the language, I've decided to compile function definitions into a fast bytecode format that can run more efficiently than the interpreter, partly by making more assumptions about variables actually being lexical. In order to stay compliant with the spec, before a call to such a function, the runtime checks if any dynamic variables are defined which would override lexicals in the function's scope (or in any functions further down the call stack); in such a case, it doesn't call the optimized version but just defaults to the slow path of interpreting off of the `lit clo`.

**Comment by luksamuk** [comment]
That caught me by surprise, I think I misunderstood the order for some reason.
Fixing this will be my next job.
